### PR TITLE
Bug fix for tester.cycle repeat: x

### PR DESCRIPTION
**Pull request by pderouen**
If tester.cycle is provided a repeat count, Link has ignored it in the past.  This fixes that bug.  However, that means patterns will run slower now if there are delays added this way.  While the new behavior is correct, it may not be desirable.  There are 2 options for avoiding unnecessary delays.

Don't add the large repeat if link is the tester:
~~~ruby
  tester.link? ? tester.cycle : tester.cycle repeat: 17000
~~~

Or, a  property can be added to globally enable/disable the new behavior:
~~~ruby
  # somewhere in the app
  tester.ignore_repeats = true if tester.link?

  #  pattern code remains unchanged
  tester.cycle repeat: 17000
~~~

### CODE REVIEW

**Comment by pderouen** [comment]
@ginty @rlaj @chrisnappi @redxeth   Do you have a preference here?

**Comment by ginty** [comment]
Hi @pderouen,

The intention is that defining a repeat count via tester.cycle should really be used when defining something like a protocol driver where you want to repeat some data for a few cycles, rather than using it to specify large delays.

The API that should be used for defining delays is tester.wait:

~~~ruby
tester.wait time_in_cycles: 17000
~~~

The distinction is important here because with the former tester.cycle case, you are explicitly telling Origen that you want X number of cycles.
In the latter case though, you are telling Origen that you want a delay and you are expressing that relative to what you think the current cycle period is, but ultimately it is the real time of the delay that is important rather than the absolute number of cycles.

Now if the user has requested a cycle period of 100ns, but Link can only deliver 1ms (for example) then you could override the wait method in the Link driver and apply the necessary adjustment to the number of cycles so that it ends up with a real time delay in the ballpark of what the user originally wanted.

By using the correct choice of API to define delays, no app-side adjustment should be required when targeting Link vs. another tester.

**Comment by pderouen** [comment]
@ginty thanks for clarifying that.  I didn't know that.  In this case I think it makes the most sense to just fix the bug without creating a way to "unfix" it.

Maybe now is the time to go ahead and ensure that tester.wait is handled correctly by link.

**Comment by pderouen** [comment]
I added the wait method to add delay.  By default it will ensure all generated cycles are sent to the server for execution and then wait the requested amount of time (using sleep).  If options[:apply_cycles] = true, it will convert the requested delay time into something close to the appropriate number of cycles.

**Comment by ginty** [comment]
Hi @pderouen, I should have mentioned it yesterday, but its preferable to implement the delay method at the individual driver level rather than the wait method:
https://github.com/Origen-SDK/origen_testers/blob/master/lib/origen_testers/timing.rb#L245

That means all the code for converting to a number of cycles is done in a central place and you only need to handle the final number of cycles.

Should the apply_cycles option enabled not be the default?

I can't imagine many people ever really knowing about and applying this option in future, and instead would simply put up with long execution times on Link.

**Comment by pderouen** [comment]
@ginty, I don't think there's any benefit in generating vector cycles for a wait request on link.  The typical use case has the main clock source as a free running clock with link only controlling the protocol clock.  On a regular ATE you want the cycles generated because that's how your main clock stays running.  On an EVB a simple time delay would be the equivalent.

I'm not opposed to having the wait method generate cycles by default.  But, I can't think of many cases where I'd want it.

**Comment by xnappo** [comment]
Yeah, certainly don't want that by default as things stand right now.  All it will do is slow things down, and right now a link cycle is not the same thing as a tester cycle.  Do we know the 'speed' of a link cycle?   If it is fairly consistent, scaling the counts might make sense.

**Comment by pderouen** [comment]
You're xnappo now?  I can only approximate the time it takes to execute a cycle.  It depends mostly on the number of pin operations that will be performed during the cycle and how long it takes the OS to respond.

**Comment by ginty** [comment]
Hi @pderouen, sorry I was reading the code wrong, we are in agreement that the correct default is to delay for the amount of time the user expects and not actually perform the cycles.

**Pull request merged**
